language: node_js

node_js:
- node

cache: yarn

install:
- yarn

before_script:
- yarn global add typescript@3.3

script:
- tsc -b --listEmittedFiles
- oclif-dev manifest
- oclif-dev readme

deploy:
  provider: npm
  email: mateusz@cholewka.com.pl
  api_key:
    secure: rsbPLYdEmmv2e1yAH/HkzHuFj+bOTURnWEjms973InVGAJVUNj0PLBpll4njWsP18HWnZXPiGz7G36jVUIsLXDoAZm3m7GRTikD5WyNoxYZuyMvD5iWL3Ov9Lghkzl0WF11nY7PGhIJHllS01T5pwxaFcuhOrTN5QVe2wJTNgKI1f/2gqU+9Pew6JhiFkbqGLsJKK7xKzUkf+Ax2z16fqObUW7i967fKePZGzlDpWkegKHqXA9nyg/LU1kAazd7ZbDy38VYCATVsH4w5tybS0NUy8TXq/GJFuMF5zO/Z6ft16AscJADALlW8zPbFHBg/W0uO0bULgCYGyxJpdovdCSc3SFBY+b8RUQ0Z9eMlMEv6A4rsiTi05Se4NhSv3XqiJsIW+PaLPHQTuuejiiAUGcXuRTk+HHsHgP+gWyLDgFsf/qHthDjow3pN1FJUPr0cXQ5vtov4XjJSvYBIJKxKwylB2zLlnxLeLfjLfoxh9Opcbyd+ny9g4XsWlpdX8kMZ2ogW8GdezaE1aGZA+jhU8sw5Pejog/KcoreRWJokH5M2gzSeBsfXAQaZOWxdu1q0v1yv2uZRIz7NR4SMTkLhvlIimbXw6Aa78XuM0zmdW776qj8F7xaYB4d0m6WC76hmB5ft4Hm7hnCg+Sls7Ig+PYKfPxB82H4KGKk+u/tqvSo=
  on:
    tags: true
    repo: mtk3d/domiurge
  skip_cleanup: true

notifications:
  email:
    recipients:
    - mateusz@cholewka.com.pl
    on_success: never
    on_failure: always
